### ISSUE TITLE
Change students status to eligible for hackathon from admin

### ISSUE THREAD

**Issue by cimendes** [LDSSA/portal#149]
**Task breakdown [updated 25 sept 2021]**

- [x] Task 1: Create functions to compute can_graduate based on Attendance table (with testing)
- [x] Task 2: Create function to compute can_attend_next based on last Specialization’s Unit’s grades (with testing)
- [x] Task 3: Add two new flags to models with default True
- [x] Task 4: https://github.com/LDSSA/portal/issues/170
- [x] Task 5: https://github.com/LDSSA/portal/issues/171
- [ ] Task 6: https://github.com/LDSSA/portal/issues/172
- [x] Task 7: https://github.com/LDSSA/portal/issues/173
- [ ] **[In progress]** Task 8: https://github.com/LDSSA/portal/issues/174
- [ ] Task 9:  Add constraint on model/db that can_attend_next can never be True when can_graduate is False
- [ ] Task 10: Add more tests around this logic

**Comment by cimendes** [comment]
Requirements:

- [ ] 
- [ ] 
- [ ]

**Comment by CatarinaSilva** [comment]
@cimendes this would be my proposal:

### Solution description

#### 1. Keeping track of students’ graduation eligibility:

* Add `can_graduate` flag to student (boolean) that has as default True (anytime a user is created this is made to true)
* Change `can_graduate` after every hackathon (to use presences information)
    * Rule: if student has attendance (using the `Attendance` mentioned below) in 1st hackathon (maybe we could add a flag `mandatory` to hackathons + all hackathons - 1, he’s eligible for graduation

```
class Attendance(models.Model):
    hackathon = models.ForeignKey(
        Hackathon, on_delete=models.CASCADE, related_name="attendance"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="attendance",
    )
    present = models.BooleanField(default=True)
    # remote = models.BooleanField(default=False)
```



#### 2. Keeping track of students’ hackathon attendance eligibility:

* Add `can_attend_next` flag to student (boolean) that has as default True (anytime a user is created this is made to true)
* Change `can_attend_next` before every hackathon (need a better definition of the trigger for this, but the verification should be based on rules
    * Rule: all units of same specialization delivered - change to True (or keep True), otherwise False



#### 3. Using information across different actions:

* Use this `can_graduate` + `can_attend_next` flag to filter the list of students in hackathons presences
* Use the `can_graduate` flag as a potential filter in the instructor’s student list view
* Add attendance column + can_graduate + can_attend_next in instructor’s student list view  (so that export csv will 


</br> 

### Potential task breakdown:
* Task 1: Create functions to compute `can_graduate` based on Attendance table (with testing)
* Task 2: Create function to compute `can_attend_next` based on last Specialization’s Unit’s grades (with testing)
* Task 3:  Add two new flags to models with default True and setup up previous functions to populate them on the desired moments:
    * `can_graduate` on closing of a hackathon
    * `can_attend_next` on closing of all units of a specialisation
    * Add constraint on model/db that `can_attend_next` can never be True when `can_graduate` is False
* Task 4:  Change hackathon  `mark attendance` page to filter by `can_attend_next` = True
* Task 5:  Add possibility of filtering by `can_graduate` on  instructor’s student list view
* Task 6:  Add attendance column + can_graduate + can_attend_next in instructor’s student list view  (so that export csv will

**Comment by CatarinaSilva** [comment]
Any fundamental thing against this? Do you mind if I take a stab at implementing it?

**Comment by hcastilho** [comment]
Looks good. Sure go ahead.

**Comment by CatarinaSilva** [comment]
update task breakdown and started linking issues for smaller tasks in body of issue :)

**Comment by Gustavo-SF** [comment]
Closing since this was already broken down into other tasks
